version: '3.1'
services:
  api:
    image: 'trenerpol'
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://trenerpol-instance.cwtvc1omxayq.eu-west-2.rds.amazonaws.com:3721/trenerpol
      - SPRING_DATASOURCE_USERNAME=OdIEWirC
      - SPRING_DATASOURCE_PASSWORD=HBgAz64HE2MwMDDL
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgresql:
    image: postgres
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST="trenerpol-instance.cwtvc1omxayq.eu-west-2.rds.amazonaws.com"
      - POSTGRES_PASSWORD=HBgAz64HE2MwMDDL
      - POSTGRES_USER=OdIEWirC
      - POSTGRES_DB=trenerpol
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
        - ./data:/var/lib/postgresql/data
